### PR TITLE
Physics Improvements

### PR DESCRIPTION
**Pull request by shinyquagsire23**
This is basically just a blanket PR for some physics changes I'm hoping to get working. As of now, the physics are a bit wonky and do not quite scale exactly to the game. Since many puzzles in the game rely on very specific jump heights, running speeds, etc, it would be best to get the physics on some things sorted out somewhat before going into deep fine-tuning.

So far this PR adds:
- Slowdown while crouching_walking
- Slowdown while moving backwards and strafing
- Running

Another issue I'm hoping to tackle is the problems in regards to jumping. As of now, there is no air resistance or capping of any sort on x/y velocities while jumping, which can allow the player to jump extremely long distances. One rather obvious example of this is when the player jumps while firing the concussion rifle. The knockback, in some cases, can send the player to the opposite end of the map within just a few frames.

To tackle jump/leap accuracy, it might be best to set up a test map to compare the stock engine vs gorc with. I might also try doing some RE on the engine itself, although I might not get anywhere that way depending on how deep I have to dig into the engine itself.

If there are any issues so far in my code, let me know so I can get that adjusted.

### CODE REVIEW

**Comment by jdmclark** [comment]
I think it's fine to use placeholder constants for now, and I think setting up a test map is a good approach to puzzling out what all of the template parameters do. However, I have two concerns:

First, crouch and run speed clamping / scaling should be implemented in the character controller. translate_camera is some leftover glue from when Gorc was more like a level viewer than a game, and just passes through the thrust vector to the character controller.

Second, this patch changes the values of some physics flags. The physics flag values are used in the original scripts and templates, so it's not safe to repurpose values unless there's convincing evidence that it's unused or incorrectly named.

**Comment by shinyquagsire23** [comment]
Yeah, it did feel a bit awkward there, and as far as physics flags go, I'm _guessing_ that running isn't in there at all. I actually looked into some of the force powers and it seems that there's a somewhat significant COG command which would be useful in terms of getting an idea of scaling:

```
SetActorExtraSpeed(player, 0.5 + rank / 2);
```

Although it also set sets it to 0 to reset, not sure if that effects running or not in the original game (I'll probably double check just in case). But perhaps it wouldn't be a horrible idea to just have an extra variable for extra speed to be appended onto the player/thing objects, and then have run modify that instead. If I were to remove the running flag from physics though, what would the best place be to put a toggle variable for that? Or should I just search around to see if it actually is a physics flag or something.

**Comment by jdmclark** [comment]
Keep in mind, JK was designed to be played with a joystick. The difference between walking and running is just the magnitude of the input. In that sense, it probably is best to handle the run/walk velocity clamping outside of the character controller.

Crouching and walking backwards should be slower, and that information is already available to the character controller. It's just a question of what speeds should be used, and where they come from - were they hard-coded in JK, or did they come from thing templates? Some other constant or hidden internal variable?

The frustrating part is that, in many cases, seemingly sensible values in scripts and levels are actually scaled by mystery constants. So even figuring out what template parameters and flags affect thing behavior doesn't rule out having to compare test levels with fraps.

**Comment by shinyquagsire23** [comment]
So I decided to do some RE on the Jedi Knight executable and I think I might have found a slew of debugging commands which might aid in getting the proper units for things. If you open JK.EXE and search for this:

```
C4 01 0F 84 B8 01 00 00 6A 00 68 EC BC 54 00 68 D0 A1 4D 00 E8
```

and replace it with this:

```
C4 01 0F 8C B8 01 00 00 6A 00 68 EC BC 54 00 68 D0 A1 4D 00 E8
```

You can enable a bunch of hidden debug commands (ie for pressing T). You can also use the -devMode parameter to give yourself an external window to input commands in. A full list of commands can be found using "help". There are some which might be helpful, or might not be, idk. There also seems to be a bunch of stuff which might aid in reversing some stuff with cogs. I'm hoping there's also some stuff in there which could be used to print out flags. I know for a fact though that they have a bunch of extra cog commands which have never even been used before, so those might be reverseable. 

EDIT: Apparently there's a coords command, so what we might be able to do is record a video where we know the coords before and after, and then determine the actual velocities used for running, walking, etc.

**Comment by shinyquagsire23** [comment]
OK, so I did some tests on running, the average speed was 1.25 units per second. Seems pretty straightforward. I basically though just took a video at 60fps in the Blades of Death map where I ran the coords command before running, ran down the long hallway, and then ran the coords command after. Then I did that a few more times, and went through frame by frame and found the exact starting point of the running, and the exact ending point where I hit the wall, did the math for each, and then averaged it out.

I'll probably go ahead and do it for walking as well, and also crouching, strafing, and walking backwards. I have a feeling that walking will be a bit slower than 1 unit per second and crouching might be slower as well.

One thing that I noticed though was that there was also a sort of running start which occurred. When running, the character will start off as walking and gradually gain speed until at running speeds. I think I ran a long enough distance though to have that averaged out. Also, the weapon swaying needs a ton of adjustment, it actually goes quite a bit faster at normal walking speeds.

EDIT: Some more speeds, these ones were actually pulled from memory rather than calculated, more efficient and accurate that way. Only downside is that the I'm actually uncertain on the scaling on these.
Walking forwards: 0.666666 (2/3)
Walking backwards: 0.333333 (1/3)
Running forwards: 1.33333 (4/3)
Running backwards: 0.666666 (2/3)
Strafe (walk): 0.5
Strafe (run): 1.0
Crouch forwards: 0.266655 (4/15?)
Crouch backwards: 0.133319 (half of crouch speed)
Acceleration/Deceleration factor: 0.05 (grabbed this by quickly resuming and escaping so only one frame played, so kinda hard to say what the units per time is. However, the value is constant after several tests)

The acceleration/deceleration factor is used when increasing and decreasing speed, and forced while in the air. So if your velocity is something like 1.3 in the air, this factor will rapidly pull it down preventing the player from shooting off too far.

**Comment by shinyquagsire23** [comment]
OK, pushed a few more commits. Now most of the actions in the game are accurate to the game's maximum speed for those actions. Acceleration and deceleration still need to be added though, because if you actually compare gorc with DF2, the speeds and animations will be the exact same, the only difference is DF2 actually has a certain timeframe where the player accelerates into those speeds.

Also, some animations tilt the camera, particularly strafing. So I might try getting that fixed. So basically my TODO list for the rest of the physics changes is
- Add acceleration/deceleration, maybe by either implementing this in the new block in update_standing (ie just add to thrust and then clamp) or having a target velocity and then the values will be applied further on.
- Implement proper swimming, also grab proper velocities for that
- Implement proper camera movement for new movements
- Making sure running is or isn't a flag, I'd rather not have false flags in once it's ready to be pushed to develop
- Other tuning

**Pull request closed without merging**
